### PR TITLE
Not Working with React Native 0.62

### PR DESCRIPTION
**Pull request by preduseldavid**
Not working with the latest version of React Native (0.62) for iOS. It gets conflict with CocoaAsyncSocket (duplicate symbols), so the the build fails

### CODE REVIEW

**Comment by theprdv** [comment]
Not working with the latest version of React Native (0.62) for iOS. It gets conflict with CocoaAsyncSocket (duplicate symbols), so the the build fails

**Comment by Overtorment** [comment]
This repo is abandoned, I suggest you send PR to an active fork, there's a bunch:

https://github.com/aprock/react-native-tcp
OR
https://github.com/hawkingnetwork/react-native-tcp
OR
https://github.com/tablexi/react-native-tcp
OR 
https://github.com/PeelTechnologies/react-native-tcp/network/members

**Comment by Rapsssito** [comment]
@Overtorment and @preduseldavid, I might also add my own repo, **[react-native-tcp-socket](https://github.com/Rapsssito/react-native-tcp-socket)**, which is **RN 62.0 compatible**.

**Comment by preduseldavid** [comment]
@Rapsssito there is a bug in your package, I used it before I switched to this package.

**Comment by Rapsssito** [comment]
@preduseldavid feel free to open an issue with your case! The repo is used in more than 17 projects without problems and I use it on production.

Your issue is probably caused by JS object handling and might have an easy fix.

**Comment by Overtorment** [comment]
we switched to https://github.com/Rapsssito/react-native-tcp-socket in production and I highly recommend it
